name: Docker build, test and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }} /loriental-grill

jobs:
  build-test:
    name: Build and smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for buildx)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image (local load)
        run: |
          docker build -t loriental-grill:ci .

      - name: Run container for smoke test
        run: |
          docker run -d --name test-container -p 8080:80 loriental-grill:ci || (docker logs test-container && exit 1)
          # give the container a few seconds to boot
          sleep 8
          curl -fS --retry 3 --retry-delay 2 http://localhost:8080 || (docker logs test-container && docker stop test-container && docker rm test-container && exit 1)
          docker stop test-container
          docker rm test-container

  build-and-push:
    name: Build & push image
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub (or other registry)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/loriental-grill:latest
            ${{ secrets.DOCKER_USERNAME }}/loriental-grill:${{ github.sha }}

  # Optional deploy step (example using SSH) - uncomment and configure secrets to use
  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Deploy to server via SSH
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USER }}
  #         key: ${{ secrets.SERVER_SSH_KEY }}
  #         script: |
  #           docker pull ${{ secrets.DOCKER_USERNAME }}/loriental-grill:latest
  #           docker stop loriental-grill || true
  #           docker rm loriental-grill || true
  #           docker run -d --restart unless-stopped --name loriental-grill -p 80:80 ${{ secrets.DOCKER_USERNAME }}/loriental-grill:latest